### ISSUE TITLE
Running hash_var causes an error 

### ISSUE THREAD

**Issue by tkr231** [vusaverse/vusa#4]
could not find function "check_installed_package"
![image](https://github.com/vusaverse/vusa/assets/175126873/9596cffd-c02f-435d-9cdc-2cf831bb93ed)

**Comment by Tomeriko96** [comment]
Thank you for creating the issue. I've successfully reproduced the issue. Upon investigation, I've identified two key points:

1. Implicit dependency: There appears to be an implicit assumption that the `vvmover` package is loaded using the library() function. This assumption may not always hold true and could be the root cause of the problem.

2. Redundant package check: The check for the `digest` package in the code is unnecessary. The DESCRIPTION file of `vusa` already lists digest as an imported package, ensuring its availability when `vusa` is loaded.

Commit 09db5e438c90d015b3dec2c672de9f6e0934cb77 removes the redundant check.
